export const SEARCH_CHAT_REQUEST = 'SEARCH_CHAT_REQUEST'
export const SEARCH_CHAT_SUCCESS = 'SEARCH_CHAT_SUCCESS'
export const SEARCH_CHAT_FAIL = 'SEARCH_CHAT_FAIL'

export const ACCESS_CHAT_REQUEST = 'ACCESS_CHAT_REQUEST'
export const ACCESS_CHAT_SUCCESS = 'ACCESS_CHAT_SUCCESS'
export const ACCESS_CHAT_FAIL = 'ACCESS_CHAT_FAIL'
export const RESET_ACCESS_CHAT = 'RESET_ACCESS_CHAT'

export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST'
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL'

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL'

export const FETCH_CHATS_REQUEST = 'FETCH_CHATS_REQUEST'
export const FETCH_CHATS_SUCCESS = 'FETCH_CHATS_SUCCESS'
export const FETCH_CHATS_FAIL = 'FETCH_CHATS_FAIL'

export const SELECTED_CHAT = 'SELECTED_CHAT'
export const CLEAR_SELECTED_CHAT = 'CLEAR_SELECTED_CHAT'

