export const ADMIN_COURSES_REQUEST = 'ADMIN_COURSES_REQUEST'
export const ADMIN_COURSES_SUCCESS = 'ADMIN_COURSES_SUCCESS'
export const ADMIN_COURSES_FAIL = 'ADMIN_COURSES_FAIL'

export const ALL_COURSES_REQUEST = 'ALL_COURSES_REQUEST'
export const ALL_COURSES_SUCCESS = 'ALL_COURSES_SUCCESS'
export const ALL_COURSES_FAIL = 'ALL_COURSES_FAIL'

export const NEW_COURSE_REQUEST = 'NEW_COURSE_REQUEST'
export const NEW_COURSE_SUCCESS = 'NEW_COURSE_SUCCESS'
export const NEW_COURSE_RESET = 'NEW_COURSE_RESET'
export const NEW_COURSE_FAIL = 'NEW_COURSE_FAIL'

export const ACCEPT_COURSE_REQUEST = 'ACCEPT_COURSE_REQUEST'
export const ACCEPT_COURSE_SUCCESS = 'ACCEPT_COURSE_SUCCESS'
export const ACCEPT_COURSE_RESET = 'ACCEPT_COURSE_RESET'
export const ACCEPT_COURSE_FAIL = 'ACCEPT_COURSE_FAIL'

export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST'
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS'
export const DELETE_COURSE_RESET = 'DELETE_COURSE_RESET'
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_FAIL'

export const UPDATE_COURSE_REQUEST = 'UPDATE_COURSE_REQUEST'
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS'
export const UPDATE_COURSE_RESET = 'UPDATE_COURSE_RESET'
export const UPDATE_COURSE_FAIL = 'UPDATE_COURSE_FAIL'

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST'
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS'
export const COURSE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL'

export const NEW_LESSON_REQUEST = 'NEW_LESSON_REQUEST'
export const NEW_LESSON_SUCCESS = 'NEW_LESSON_SUCCESS'
export const NEW_LESSON_RESET = 'NEW_LESSON_RESET'
export const NEW_LESSON_FAIL = 'NEW_LESSON_FAIL'

export const GET_LESSONS_REQUEST = 'GET_LESSONS_REQUEST'
export const GET_LESSONS_SUCCESS = 'GET_LESSONS_SUCCESS'
export const GET_LESSONS_FAIL = 'GET_LESSONS_FAIL'

export const GET_LESSON_REQUEST = 'GET_LESSONS_REQUEST'
export const GET_LESSON_SUCCESS = 'GET_LESSONS_SUCCESS'
export const GET_LESSON_FAIL = 'GET_LESSONS_FAIL'

export const DELETE_LESSON_REQUEST = 'DELETE_LESSON_REQUEST'
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS'
export const DELETE_LESSON_RESET = 'DELETE_LESSON_RESET'
export const DELETE_LESSON_FAIL = 'DELETE_LESSON_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'