export const MY_COURSES_REQUEST = 'MY_COURSES_REQUEST'
export const MY_COURSES_SUCCESS = 'MY_COURSES_SUCCESS'
export const MY_COURSES_FAIL = 'MY_COURSES_FAIL'

export const CREATOR_COURSES_REQUEST = 'CREATOR_COURSES_REQUEST'
export const CREATOR_COURSES_SUCCESS = 'CREATOR_COURSES_SUCCESS'
export const CREATOR_COURSES_FAIL = 'CREATOR_COURSES_FAIL'

export const ADMIN_COURSES_REQUEST = 'ADMIN_COURSES_REQUEST'
export const ADMIN_COURSES_SUCCESS = 'ADMIN_COURSES_SUCCESS'
export const ADMIN_COURSES_FAIL = 'ADMIN_COURSES_FAIL'

export const REGULAR_COURSES_REQUEST = 'REGULAR_COURSES_REQUEST'
export const REGULAR_COURSES_SUCCESS = 'REGULAR_COURSES_SUCCESS'
export const REGULAR_COURSES_FAIL = 'REGULAR_COURSES_FAIL'

export const ALL_COURSES_REQUEST = 'ALL_COURSES_REQUEST'
export const ALL_COURSES_SUCCESS = 'ALL_COURSES_SUCCESS'
export const ALL_COURSES_FAIL = 'ALL_COURSES_FAIL'

export const NEW_COURSE_REQUEST = 'NEW_COURSE_REQUEST'
export const NEW_COURSE_SUCCESS = 'NEW_COURSE_SUCCESS'
export const NEW_COURSE_RESET = 'NEW_COURSE_RESET'
export const NEW_COURSE_FAIL = 'NEW_COURSE_FAIL'

export const ACCEPT_COURSE_REQUEST = 'ACCEPT_COURSE_REQUEST'
export const ACCEPT_COURSE_SUCCESS = 'ACCEPT_COURSE_SUCCESS'
export const ACCEPT_COURSE_RESET = 'ACCEPT_COURSE_RESET'
export const ACCEPT_COURSE_FAIL = 'ACCEPT_COURSE_FAIL'

export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST'
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS'
export const DELETE_COURSE_RESET = 'DELETE_COURSE_RESET'
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_FAIL'

export const UPDATE_COURSE_REQUEST = 'UPDATE_COURSE_REQUEST'
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS'
export const UPDATE_COURSE_RESET = 'UPDATE_COURSE_RESET'
export const UPDATE_COURSE_FAIL = 'UPDATE_COURSE_FAIL'

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST'
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS'
export const COURSE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL'

export const NEW_LESSON_REQUEST = 'NEW_LESSON_REQUEST'
export const NEW_LESSON_SUCCESS = 'NEW_LESSON_SUCCESS'
export const NEW_LESSON_RESET = 'NEW_LESSON_RESET'
export const NEW_LESSON_FAIL = 'NEW_LESSON_FAIL'

export const GET_LESSONS_REQUEST = 'GET_LESSONS_REQUEST'
export const GET_LESSONS_SUCCESS = 'GET_LESSONS_SUCCESS'
export const GET_LESSONS_FAIL = 'GET_LESSONS_FAIL'

export const GET_LESSON_REQUEST = 'GET_LESSONS_REQUEST'
export const GET_LESSON_SUCCESS = 'GET_LESSONS_SUCCESS'
export const GET_LESSON_FAIL = 'GET_LESSONS_FAIL'

export const DELETE_LESSON_REQUEST = 'DELETE_LESSON_REQUEST'
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS'
export const DELETE_LESSON_RESET = 'DELETE_LESSON_RESET'
export const DELETE_LESSON_FAIL = 'DELETE_LESSON_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST'
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS'
export const GET_TOPICS_FAIL = 'GET_TOPICS_FAIL'

export const NEW_TOPIC_REQUEST = 'NEW_TOPIC_REQUEST'
export const NEW_TOPIC_SUCCESS = 'NEW_TOPIC_SUCCESS'
export const NEW_TOPIC_RESET = 'NEW_TOPIC_RESET'
export const NEW_TOPIC_FAIL = 'NEW_TOPIC_FAIL'

export const DELETE_TOPIC_REQUEST = 'DELETE_TOPIC_REQUEST'
export const DELETE_TOPIC_SUCCESS = 'DELETE_TOPIC_SUCCESS'
export const DELETE_TOPIC_RESET = 'DELETE_TOPIC_RESET'
export const DELETE_TOPIC_FAIL = 'DELETE_TOPIC_FAIL'

export const UPDATE_TOPIC_REQUEST = 'UPDATE_TOPIC_REQUEST'
export const UPDATE_TOPIC_SUCCESS = 'UPDATE_TOPIC_SUCCESS'
export const UPDATE_TOPIC_RESET = 'UPDATE_TOPIC_RESET'
export const UPDATE_TOPIC_FAIL = 'UPDATE_TOPIC_FAIL'

export const GET_QUIZS_REQUEST = 'GET_QUIZS_REQUEST'
export const GET_QUIZS_SUCCESS = 'GET_QUIZS_SUCCESS'
export const GET_QUIZS_FAIL = 'GET_QUIZS_FAIL'

export const NEW_QUIZ_REQUEST = 'NEW_QUIZ_REQUEST'
export const NEW_QUIZ_SUCCESS = 'NEW_QUIZ_SUCCESS'
export const NEW_QUIZ_RESET = 'NEW_QUIZ_RESET'
export const NEW_QUIZ_FAIL = 'NEW_QUIZ_FAIL'

export const DELETE_QUIZ_REQUEST = 'DELETE_QUIZ_REQUEST'
export const DELETE_QUIZ_SUCCESS = 'DELETE_QUIZ_SUCCESS'
export const DELETE_QUIZ_RESET = 'DELETE_QUIZ_RESET'
export const DELETE_QUIZ_FAIL = 'DELETE_QUIZ_FAIL'

export const UPDATE_QUIZ_REQUEST = 'UPDATE_QUIZ_REQUEST'
export const UPDATE_QUIZ_SUCCESS = 'UPDATE_QUIZ_SUCCESS'
export const UPDATE_QUIZ_RESET = 'UPDATE_QUIZ_RESET'
export const UPDATE_QUIZ_FAIL = 'UPDATE_QUIZ_FAIL'

export const NEW_DOCUMENT_REQUEST = 'NEW_DOCUMENT_REQUEST'
export const NEW_DOCUMENT_SUCCESS = 'NEW_DOCUMENT_SUCCESS'
export const NEW_DOCUMENT_RESET = 'NEW_DOCUMENT_RESET'
export const NEW_DOCUMENT_FAIL = 'NEW_DOCUMENT_FAIL'

export const GET_DOCUMENTS_REQUEST = 'GET_DOCUMENTS_REQUEST'
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS'
export const GET_DOCUMENTS_FAIL = 'GET_DOCUMENTS_FAIL'

export const GET_DOCUMENT_REQUEST = 'GET_DOCUMENTS_REQUEST'
export const GET_DOCUMENT_SUCCESS = 'GET_DOCUMENTS_SUCCESS'
export const GET_DOCUMENT_FAIL = 'GET_DOCUMENTS_FAIL'

export const DELETE_DOCUMENT_REQUEST = 'DELETE_DOCUMENT_REQUEST'
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS'
export const DELETE_DOCUMENT_RESET = 'DELETE_DOCUMENT_RESET'
export const DELETE_DOCUMENT_FAIL = 'DELETE_DOCUMENT_FAIL'


export const GET_NOTES_REQUEST = 'GET_NOTES_REQUEST'
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS'
export const GET_NOTES_FAIL = 'GET_NOTES_FAIL'

export const NEW_NOTE_REQUEST = 'NEW_NOTE_REQUEST'
export const NEW_NOTE_SUCCESS = 'NEW_NOTE_SUCCESS'
export const NEW_NOTE_RESET = 'NEW_NOTE_RESET'
export const NEW_NOTE_FAIL = 'NEW_NOTE_FAIL'

export const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST'
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS'
export const DELETE_NOTE_RESET = 'DELETE_NOTE_RESET'
export const DELETE_NOTE_FAIL = 'DELETE_NOTE_FAIL'

export const UPDATE_NOTE_REQUEST = 'UPDATE_NOTE_REQUEST'
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS'
export const UPDATE_NOTE_RESET = 'UPDATE_NOTE_RESET'
export const UPDATE_NOTE_FAIL = 'UPDATE_NOTE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'