export const ALL_FOLLOWING_REQUEST = 'ALL_FOLLOWING_REQUEST'
export const ALL_FOLLOWING_SUCCESS = 'ALL_FOLLOWING_SUCCESS'
export const ALL_FOLLOWING_FAIL = 'ALL_FOLLOWING_FAIL'

export const ALL_FOLLOWER_REQUEST = 'ALL_FOLLOWER_REQUEST'
export const ALL_FOLLOWER_SUCCESS = 'ALL_FOLLOWER_SUCCESS'
export const ALL_FOLLOWER_FAIL = 'ALL_FOLLOWER_FAIL'

export const NEW_FOLLOW_REQUEST = 'NEW_FOLLOW_REQUEST'
export const NEW_FOLLOW_SUCCESS = 'NEW_FOLLOW_SUCCESS'
export const NEW_FOLLOW_RESET = 'NEW_FOLLOW_RESET'
export const NEW_FOLLOW_FAIL = 'NEW_FOLLOW_FAIL'

export const DELETE_FOLLOW_REQUEST = 'DELETE_FOLLOW_REQUEST'
export const DELETE_FOLLOW_SUCCESS = 'DELETE_FOLLOW_SUCCESS'
export const DELETE_FOLLOW_RESET = 'DELETE_FOLLOW_RESET'
export const DELETE_FOLLOW_FAIL = 'DELETE_FOLLOW_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'