export const GET_NOTIFIES_REQUEST = 'GET_NOTIFIES_REQUEST'
export const GET_NOTIFIES_SUCCESS = 'GET_NOTIFIES_SUCCESS'
export const GET_NOTIFIES_FAIL = 'GET_NOTIFIES_FAIL'

export const DELETE_ALL_NOTIFIES_REQUEST = 'DELETE_ALL_NOTIFIES_REQUEST'
export const DELETE_ALL_NOTIFIES_SUCCESS = 'DELETE_ALL_NOTIFIES_SUCCESS'
export const DELETE_ALL_NOTIFIES_RESET = 'DELETE_ALL_NOTIFIES_RESET'
export const DELETE_ALL_NOTIFIES_FAIL = 'DELETE_LESSON_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'