export const POST_QUESTION = 'POST_QUESTION'
export const POST_ANSWER = 'POST_ANSWER'
export const FETCH_ALL_QUESTIONS = 'FETCH_ALL_QUESTIONS'

export const MARK_SOLVED_REQUEST = 'MARK_SOLVED_REQUEST'
export const MARK_SOLVED_SUCCESS = 'MARK_SOLVED_SUCCESS'
export const MARK_SOLVED_RESET = 'MARK_SOLVED_RESET'
export const MARK_SOLVED_FAIL = 'MARK_SOLVED_FAIL'