export const ALL_REGISTER_COURSES_REQUEST = 'ALL_REGISTER_COURSES_REQUEST'
export const ALL_REGISTER_COURSES_SUCCESS = 'ALL_REGISTER_COURSES_SUCCESS'
export const ALL_REGISTER_COURSES_FAIL = 'ALL_REGISTER_COURSES_FAIL'

export const NEW_REGISTER_COURSE_REQUEST = 'NEW_REGISTER_COURSE_REQUEST'
export const NEW_REGISTER_COURSE_SUCCESS = 'NEW_REGISTER_COURSE_SUCCESS'
export const NEW_REGISTER_COURSE_RESET = 'NEW_REGISTER_COURSE_RESET'
export const NEW_REGISTER_COURSE_FAIL = 'NEW_REGISTER_COURSE_FAIL'

export const DELETE_REGISTER_COURSE_REQUEST = 'DELETE_REGISTER_COURSE_REQUEST'
export const DELETE_REGISTER_COURSE_SUCCESS = 'DELETE_REGISTER_COURSE_SUCCESS'
export const DELETE_REGISTER_COURSE_RESET = 'DELETE_REGISTER_COURSE_RESET'
export const DELETE_REGISTER_COURSE_FAIL = 'DELETE_REGISTER_COURSE_FAIL'

export const UPDATE_REGISTER_COURSE_REQUEST = 'UPDATE_REGISTER_COURSE_REQUEST'
export const UPDATE_REGISTER_COURSE_SUCCESS = 'UPDATE_REGISTER_COURSE_SUCCESS'
export const UPDATE_REGISTER_COURSE_RESET = 'UPDATE_REGISTER_COURSE_RESET'
export const UPDATE_REGISTER_COURSE_FAIL = 'UPDATE_REGISTER_COURSE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'