export const ALL_WISH_LIST_REQUEST = 'ALL_WISH_LIST_REQUEST'
export const ALL_WISH_LIST_SUCCESS = 'ALL_WISH_LIST_SUCCESS'
export const ALL_WISH_LIST_FAIL = 'ALL_WISH_LIST_FAIL'

export const NEW_WISH_LIST_REQUEST = 'NEW_WISH_LIST_REQUEST'
export const NEW_WISH_LIST_SUCCESS = 'NEW_WISH_LIST_SUCCESS'
export const NEW_WISH_LIST_RESET = 'NEW_WISH_LIST_RESET'
export const NEW_WISH_LIST_FAIL = 'NEW_WISH_LIST_FAIL'

export const DELETE_WISH_LIST_REQUEST = 'DELETE_WISH_LIST_REQUEST'
export const DELETE_WISH_LIST_SUCCESS = 'DELETE_WISH_LIST_SUCCESS'
export const DELETE_WISH_LIST_RESET = 'DELETE_WISH_LIST_RESET'
export const DELETE_WISH_LIST_FAIL = 'DELETE_WISH_LIST_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'